apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-app.fullname" . }}-config
  labels:
    app: {{ include "my-app.name" . }}
data:
  customValue1: {{ .Values.configmap.customValue1 | quote }}
  customValue2: {{ .Values.configmap.customValue2 | quote }}
