replicaCount: 2
serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true  
  annotations: {}  
  hosts:
    - host: "localhost"
      paths:
        - path: /
          pathType: Prefix
  tls: []

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targerPort: 80

configmap:
  customValue1: "Hello"
  customValue2: "World"
